# Generated by Django 6.0 on 2025-12-06 12:46

from django.db import migrations
from django.contrib.auth.models import Group


def create_groups(apps, schema_editor):
    Group.objects.get_or_create(name='customer')
    Group.objects.get_or_create(name='personal')
    Group.objects.get_or_create(name='admin')


def reverse_create_groups(apps, schema_editor):
    Group.objects.filter(name__in=['customer', 'personal', 'admin']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_phone'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_create_groups),
    ]
