# Generated by Django 6.0 on 2025-12-09 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=200)),
                ('tag', models.CharField(blank=True, help_text='Short tag or SKU identifier', max_length=50)),
                ('serial_number', models.CharField(help_text='Manufacturer‑assigned serial number', max_length=100, unique=True)),
                ('price_for_company', models.DecimalField(decimal_places=2, help_text='Price when sold to a company', max_digits=10)),
                ('price_for_customer', models.DecimalField(decimal_places=2, help_text='Price when sold to an end‑customer', max_digits=10)),
                ('count', models.PositiveIntegerField(default=0, help_text='Current stock quantity')),
                ('offer', models.BooleanField(default=False, help_text='Whether the product is currently on offer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ['-created_at'],
            },
        ),
    ]
