# Generated by Django 6.0 on 2025-12-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
        migrations.AddField(
            model_name='product',
            name='offer_type',
            field=models.CharField(choices=[('percent', 'Percent\u202f%'), ('price', 'Fixed price')], default='percent', help_text='Select whether the offer is a percentage discount or a fixed‑price discount', max_length=7),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount – either a percentage or a fixed price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_for_company',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_for_customer',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
