# Generated by Django 6.0.8 on 2026-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_remove_product_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='offer_type',
            field=models.CharField(choices=[('percent', 'Percent %'), ('price', 'Fixed price')], default='percent', help_text='Select whether the offer is a percentage discount or a fixed‑price discount', max_length=7),
        ),
    ]
