# Generated by Django 6.0.8 on 2026-08-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktor', '0002_alter_faktorbuy_options_alter_faktorsell_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktorbuy',
            name='supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
