# Generated by Django 6.0.8 on 2026-08-30 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faktor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faktorbuy',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='faktorsell',
            options={'ordering': ['-date', '-id']},
        ),
        migrations.AddField(
            model_name='faktorbuy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faktorbuy',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='faktorbuy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='faktorsell',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
