# Generated by Django 6.0 on 2025-12-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faktor", "0003_faktoritem"),
    ]

    operations = []
