# Generated by Django 6.0 on 2025-12-17 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faktor", "0004_auto_20251217_1643"),
    ]

    operations = []
